### ISSUE TITLE
Imposible to use the proxy: Proxy error for module 'module_name': dial tcp 127.0.0.1:9531: connect: connection refused

### ISSUE THREAD

**Issue by Tr3yWay996** [QubitProducts/exporter_exporter#104]
All is in the title, whenever I go over the exporter module I made, any of the two, it returns this error with its corresponding port.
I can see it tries to access 127.0.0.1 but idk how to change it to 10.0.0.235.
Anyone can help ? I really need two diff exports on one Prometheus install for two dashboards on Grafana

**Comment by britcey** [comment]
It'd help if you actually shared your config.

I _think_ you're asking for something like:

```
---
module_name:
  method: http
  http:
    address: 10.0.0.235
    port: 9531
```

**Comment by Tr3yWay996** [comment]
> It'd help if you shared your config.
> 
> I _think_ you're asking for something like:
> 
> ```
> ---
> module_name:
>   method: http
>   http:
>     address: 10.0.0.235
>     port: 9531
> ```

Honestly I'm sorry for forgetting to give anything else for you guys to help me, I've been quite busy, but this is my config for the expexp.yaml file
```
defaultModule: pterodactyl # called if "module" param is not supplied
modules:
  pterodactyl:
    method: http
    http:
       port: 9531

  MCstats:
    method: http
    http:
       port: 19565
```

And my Prometheus config is the following:

```
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'expexp_metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9999']
  - job_name: 'pterodactyl'
    scrape_interval: 1s
    metrics_path: /proxy
    params:
      module:
        - cadvisor
    static_configs:
      - targets: ['localhost:9531']
  - job_name: 'MCstats'
    scrape_interval: 1s
    metrics_path: /proxy
    params:
      module:
        - mtail
    static_configs:
      - targets: ['localhost:19565']
```
