### ISSUE TITLE
"path" prevents query strings

### ISSUE THREAD

**Issue by mozai** [QubitProducts/exporter_exporter#17]
Goal:
I wish to use exporter_exporter to safely export metrics about the local consul daemon.  Consul already cooperates with prometheus by provding a prometheus-compatible metrics output if I ask properly.

What I did:  
```yaml
modules:
  consul:
    http: { path: '/v1/agent/metrics?format=prometheus', port:8500 }
    method: http
```

What I expected:  
  curl http://localhost:9999/proxy?module=consul   would return the same data that I get from curl http://localhost:8500/v1/agent/metrics?format=prometheus

What I got:  
An error has occurred during metrics gathering: text format parsing error in line 1: invalid metric name

Extra information:  
running a strace on exporter_exporter (I don't have tcpdump on this machine) I can see that exporter_exporter is sending an http request "GET /v1/agent/metrics%3Fformat..."

**Comment by mozai** [comment]
An unsatisfactory workaround:

```yaml
  consul:
    exec: { command: wget, args: [ "-q", "-O-", "http://localhost:8500/v1/agent/metrics?format=prometheus" ] }
    method: exec
    timeout: 1s
```

Using 'wget' instead of the customary 'curl' because wget seems more popular on the Debian boxes I'm looking after.
