### ISSUE TITLE
Support for cached scrapping

### ISSUE THREAD

**Issue by michael-doubez** [QubitProducts/exporter_exporter#26]
Sometimes, I need to time the scraping of an endpoint or to run a script less frequently than the minimum scrape interval (~5min in prometheus before declaring the data stale). This may happens when the scraping may have a cost (contention, costly operations or on weak servers) and 

- you have multiple prometheus scraping for resiliency reasons
- a costly scripts such as one fectching a big database is run 

The idea would be to add the possibility to cache the result of the scrape and set a stamp on it. When the next scrape arrives

- if the elapsed time is less than the value configured, server the cached data
- otherwise scrape as usual and memorize the result

Currently, the only way to achieve that is to write the result in a promfile, execute the script at the wanted interval and use node_exporter to collect it. It adds a lot of setup for such a simple use case.

In terms  of configuration, it could be something similar to HTTP configuration:
```
 somescript:
    method: exec
    ...
    cache:
        enabled: True
        max_age: 30m
    exec:
      command: /tmp/don_t_launch_that_too_often.sh
```

Another nice addition for the HTTP method would be the possibility to make a HEAD request on the endpoint to at least check if it is up but this would depend on the exporter supporting it.
