### ISSUE TITLE
Additional metadata

### ISSUE THREAD

**Issue by LDaneliukas** [QubitProducts/exporter_exporter#36]
We're looking for utilizing exporter_exporter to expose additional metadata about each module that would then be consumed by third-party systems via the JSON response.

Currently, what we're using is `labels`. I.e. each module has a section of `labels` that is also exposed via JSON and can then be used by another system which constructs scrape targets for `file_sd`. Note, these aren't actually added to the metrics themselves by exporter_exporter as it still only acts as a proxy. Would that be something that could be added to exporter_exporter?

E.g.
```
modules:
  node:
    method: http
    http:
       port: 9100
    labels:
       labelname: labelval
       labelname2: labelval2
```

and

```
type moduleConfig struct {
	Method  string                 `yaml:"method"`
	Timeout time.Duration          `yaml:"timeout"`
	Labels  map[string]string      `yaml:"labels"`
```

That's pretty much it, we're not actually doing anything more than exposing it in the json response.
