### ISSUE TITLE
Verify does not work with OpenMetrics

### ISSUE THREAD

**Issue by xonvanetta** [QubitProducts/exporter_exporter#84]
Wanted to make a PR but it seems like there is no solution near.
Did not find a parser for OpenMetrics so could not create a PR here.

https://github.com/prometheus/client_golang/issues/829

Workaround for now is to skip verify:
```
modules:
  mimir:
    method: http
    http:
      verify: false
      port: 8080
```

Error code from exporter_exporter is:
`ERRO[0003] Verification for module 'mimir' failed: Failed to decode metrics from proxied server: text format parsing error in line 89: unknown metric type "unknown"`
