### ISSUE TITLE
Support running as a sokcs5 proxy

### ISSUE THREAD

**Issue by thomasf** [QubitProducts/exporter_exporter#9]
I think this is doable when prometheus is compiled with go 1.9 and gets socks5
proxy support for it's `proxy_url` argument.

something like this could work where node:1 is resolved by the socks proxy to
match a module named node in exporter_exporter as the first entry in the node
exporter section.

```yml
  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
      - targets: ['node:1']
    scheme: https
    proxy_url: "socks5://localhost:3000"
    tls_config:
      ca_file: ca.crt
      key_file: client.key
      cert_file: client.crt
      server_name: localhost

```

It get's interesting when we suddenly have a process cluster running on a node
which exporterexporter needs to pick up.

One could imagine something like this:

```yml
modules:
  myapp:
    method: http
    http:
      ports: 7000-7032

```

which would map to scrapable myqpp-targets 1-16

```yml
  - job_name: 'myapp'
    scrape_interval: 1s
    static_configs:
      - targets: ['myapp:1', 'myapp:2', 'myapp:3', 'myapp:4', 'myapp:5', 'myapp:6', ....
    scheme: https
    proxy_url: "socks5://localhost:3000"
    tls_config:
      ca_file: ca.crt
      key_file: client.key
      cert_file: client.crt
      server_name: localhost
```

As exporterexporter works right now I need one job for each `myapp` process in that host local application cluster which is the main problem I want to solve.
